### ISSUE TITLE
문제에 대한 정보를 README에 적는 기능

### ISSUE THREAD

**Issue by HyeockJinKim** [ISKU/BOJ-AutoCommit#1]
BOJ에서 풀었던 문제들에 각 문제로의 링크와 깃헙에서의 코드로의 링크를 README.md에 적어 관리할 수 있으면 좋을 것 같습니다.

**Comment by PARKINHYO** [comment]
BOJ password: 로 안넘어가네요ㅠ

**Comment by ISKU** [comment]
@PARKINHYO 
새로운 이슈를 등록해주세요.
