### ISSUE TITLE
원격저장소로의 push 오류

### ISSUE THREAD

**Issue by hy38** [ISKU/BOJ-AutoCommit#2]
안녕하세요,
* ERROR: [git_all] [push: 128] 라는 에러메세지와 함께 깃허브 레포지토리의 푸시가 안되는 오류가 발생하였습니다.
로컬저장소에 문제 소스코드가 저장이 되는것으로 보아 깃으로의 푸시과정에 문제가 있는 것 같습니다.
어떻게 해결해야 할까요?

![image](https://user-images.githubusercontent.com/34434143/53679144-ff611d80-3d0b-11e9-8eec-76c353d4bc03.png)

**Comment by ISKU** [comment]
안녕하세요! @hy38 
먼저 이 툴에 관심을 가져 주셔서 감사합니다.

해당 에러는 git push 명령을 실행하는 도중 에러가 발생하여 exit code 128을 반환받은 것입니다.
아마도 GitHub 계정의 아이디와 비밀번호를 정확히 입력하지 않아 생긴 문제일 확률이 높습니다.
툴을 실행할 때, GitHub 계정에 로그인하는 부분은 아직 예외처리가 되어있지 않습니다.
이는 다음에 개발하여 업데이트 할 예정입니다.

현재 git push 명령을 실행할 때, 보안 문제로 에러에 관한 log를 출력하고 있지 않습니다.
만약 GitHub 계정 정보를 정확히 입력하였는데도 같은 에러가 발생한다면,
툴 실행시 clone 되는 local repository에서 직접 git push 명령을 실행해보시고,
이때에도 에러가 발생한다면 출력되는 log를 올려주세요!

감사합니다.

**Comment by hy38** [comment]
안녕하세요, @ISKU 

github의 계정정보는 일치하고, commit까지 이루어졌지만, push가 어떤방식으로간에 문제가 있는것으로 생각됩니다.
git bash에서 push를 하니 정상적으로 업로드되는것을 파악했습니다!
보안문제로 인한 에러 log 미표기가 아쉽습니다..

수동으로 push를 진행하고 있긴 하지만, 저에겐 충분히 도움이 되는 툴입니다!
감사합니다.

**Comment by ISKU** [comment]
@hy38 

git push 명령과 관련된 log를 볼 수 있도록 ea0b7c88466e9617207e39ac65dd75d74059018f 에 코드를 추가하였습니다.
확인 부탁드리고, 만약 에러가 확인 가능하면 이 이슈를 다시 열거나 새로운 이슈를 등록해주세요.

감사합니다.
